### ISSUE TITLE
konversi foto profil ke base 64 saat insert data baru admin dan mahasiswa belum bekerja dengan baik

### ISSUE THREAD

**Issue by vanstevanzaky** [andromeda-hebat/FINALIS-JTI-WEB#201]
![image](https://github.com/user-attachments/assets/e975c046-b294-4ba6-9b7f-b32d184d9914)
indikasi saat ini kemungkinan ada dipengambilan data file gambar foto profile

**Comment by FarrelAD** [comment]
masalah di atas sepertinya hanya terjadi di kasus itu saja. Untuk pengujian selanjutnya tidak ditemukan kejanggalan
